uint8 levelflag
uint16 commversion              # Old version Aliengo does not have
uint16 robotid                  # Old version Aliengo does not have
uint32 sn                       # Old version Aliengo does not have
uint8 bandwidth                 # Old version Aliengo does not have
uint8 mode
float32 forwardspeed
float32 sidespeed
float32 rotatespeed
float32 bodyheight
float32 footraiseheight
float32 yaw
float32 pitch
float32 roll
LED[4] led
uint8[40] wirelessremote
uint8[40] appremote             # Old version Aliengo does not have
uint32 reserve                  # Old version Aliengo does not have
int32 crc
