uint8 levelflag
uint16 commversion              # Old version Aliengo does not have
uint16 robotid                  # Old version Aliengo does not have
uint32 sn                       # Old version Aliengo does not have
uint8 bandwidth                 # Old version Aliengo does not have
MotorCmd[20] motorcmd
LED[4] led
uint8[40] wirelessremote
uint32 reserve                  # Old version Aliengo does not have
uint32 crc

Cartesian[4] ff               # will delete # Old version Aliengo does not have
